[build.environment]
GO_VERSION = "1.26.4"
HUGO_VERSION = "0.163.3"
NODE_VERSION = "24"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"
